---
- include_tasks: autodetect.yml
  # We need to know the engine and emulator if we're creating any new VMs.
  when: "libvirt_vms | rejectattr('state', 'eq', 'absent')"

- include_tasks: volumes.yml
  with_items: "{{ libvirt_vms }}"
  loop_control:
    loop_var: vm
  when: (vm.state | default('present')) == 'present'

- include_tasks: vm.yml
  with_items: "{{ libvirt_vms }}"
  loop_control:
    loop_var: vm
  when: (vm.state | default('present')) == 'present'

- include_tasks: destroy-volumes.yml
  with_items: "{{ libvirt_vms }}"
  loop_control:
    loop_var: vm
  when: (vm.state | default('present')) == 'absent'

- include_tasks: destroy-vm.yml
  with_items: "{{ libvirt_vms }}"
  loop_control:
    loop_var: vm
  when: (vm.state | default('present')) == 'absent'
