---

- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: vars

- name: Install custom yum repositories
  # Although argument splatting is marked as deprecated:
  #
  # [DEPRECATION WARNING]: Using variables for task params is unsafe,
  # especially if the variables come from an external source like facts. This
  # feature will be removed in a future release.
  #
  # The core team had a a change of heart and it is actually being preserved:
  # https://github.com/ansible/ansible/pull/43798
  yum_repository: "{{ item }}"
  loop: "{{ libvirt_vm_custom_yum_repos | default([]) }}"
  become: true

- name: Install custom packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ libvirt_vm_extra_packages }}"

